HospitalRun/components

- .github/CONTRIBUTING.md
- README.md
> WIP: Update README.md

- README.md
- commitlint.config.js
- package.json
- src/components/Graph/index.tsx
- src/index.tsx
- Adds support to automate versioning and changelog generation
**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**
- [standard-version](https://bundlephobia.com/result?p=standard-version@7.0.0)
- [commitlint](https://bundlephobia.com/result?p=@commitlint/cli@8.1.0)
> WIP: Adds conventional commit support

- .gitignore
- .releaserc.js
- README.md
- commitlint.config.js
- package.json
Adds commitizen to align with other repos
- Commitizen
> Adds Commitizen

- .releaserc.js
- package.json
> :green_heart: (release) Updates releaserc

- README.md
Fixes #[replace brackets with the issue number that your pull request addresses].
- [list out summary of changes here]
- [list out summary of changes here]
- [list out summary of changes here]
- [etc]
**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**
- [Link of the new dependency]
- [Link of the new dependency]
- [etc]
*Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)*
> :docs: (readme) Updates core team

- package.json
Adds react-bootstrap as peer dependency
- simply adds react-bootstrap as peer dependency
> :bug: (deps) Adds react-boostrap as peer dep

- azure-pipeline.yml
- build/azure-pipeline-npm.yml
- build/azure-pipelines-yarn.yml
- Adds separate build task for npm and yarn
- Adds seperate build  for Mac, Ubuntu and Windows
> ci(devops): improves azure pipeline ci

- package.json
- test-setup.ts
- test/bargraph.test.tsx
- test/linegraph.test.tsx
- test/piegraph.test.tsx
- test/spinner.test.tsx
Fixes #6.
- Adds enzyme
- Refactors existing tests
**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**
- [enzyme](https://bundlephobia.com/result?p=enzyme@3.10.0)
- [enzyme-adapter-react-16](https://bundlephobia.com/result?p=enzyme-adapter-react-16@1.14.0)
- @types/enzyme
All new dependencies are dev dependencies
> Enzyme testing

- .github/CONTRIBUTING.md
- README.md
Updates README and CONTRIBUTING documents.
> Docs update

- README.md
- src/components/Badge/Badge.tsx
- src/components/Button/Button.tsx
- src/components/Pill/Pill.tsx
- Changes some react-bootstrap components imports to reduce bundle size
> fix(imports): reduces bundle size using specific modules imports

- .gitignore
- .storybook/webpack.config.js
- stories/badges.stories.tsx
- stories/buttons.stories.tsx
- stories/confirm.stories.tsx
- stories/graphs.stories.tsx
- stories/icons.stories.tsx
- stories/pills.stories.tsx
- stories/spinner.stories.tsx
- stories/toaster.stories.tsx
- stories/tsconfig.json
- tsconfig.json
Fixes #55 
- adds `baseUrl` and `paths` back to `tsconfig.json`
> fix(toolchain): fixes issue with storybook not properly building

- .github/workflows/ci.yml
> ci(github): fixes github ci yaml

- src/components/TextInput/TextInput.tsx
- stories/textinput.stories.tsx
- test/textinput.test.tsx
- Adds placeholder for text input
> feat(textinput): add placeholder for text input

- src/components/Badge/Badge.tsx
- src/components/Button/Button.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Icon/Icon.tsx
- src/components/Navbar/Navbar.tsx
- src/components/Pill/Pill.tsx
- src/components/Radio/Radio.tsx
- src/components/Select/Select.tsx
- src/components/Spinner/Spinner.tsx
- src/components/Switch/Switch.tsx
- src/components/TextField/TextField.tsx
- src/components/TextInput/TextInput.tsx
- test/navbar.test.tsx
- Switch components to use functional components
- Properly use default props
> refactors components to use functional components where possible

- src/components/TextField/TextField.tsx
- src/components/TextInput/TextInput.tsx
- fix(textinput): change event type to ChangeEvent
- fix(text): change event type to ChangeEvent
> Change event

- src/components/Navbar/Navbar.tsx
- stories/navbar.stories.tsx
- test/linegraph.test.tsx
- test/navbar.test.tsx
- fix typo in onSearchButtonClick function name
> fix(navbar): fix typo in onSearchButtonClick function name

- package.json
Fixes #106
- Updates TypeScript to 3.7.2
> chore(deps): update typescript

- src/components/Checkbox/Checkbox.tsx
- stories/checkbox.stories.tsx
- test/checkbox.test.tsx
Fixes #155 
Added `className` and `style` props to checkbox, corresponding tests and stories.
**Additional Notes**
I made this its own PR because it includes a minor refactoring and I wasn't sure you'd be ok with that.
> feat(checkbox): add className and style props

- package.json
- src/components/Panel/Panel.tsx
- src/components/Panel/index.tsx
- stories/panel.stories.css
- stories/panel.stories.tsx
- stories/panel.stories.tsx.rej
Fixes #138 .
- An optional header
- A required body
- An optional footer
- Ability to be collapsible
**Newly added dependencies with [Bundlephobia](https://bundlephobia.com/) links:**
- rsuite
> feat(panels): adds panel component

- src/components/Label/Label.tsx
- src/components/Panel/Panel.tsx
adds pointer when cursor is hovered over collapse/expand icon on the collapsible panel
fix #182
Fixes #182.
- Adds cursor CSS
- Label.tsx was changed by linting on commit
> fix(collapsible panel): adds pointer when cursor is hovered over icon

- scss/main.scss
Fixes hospitalrun/hospitalrun-frontend#1718
- fix import syntax
> fix(scss): fix imports to external dependencies

- src/components/Typeahead/Typeahead.tsx
- stories/typeahead.stories.tsx
- test/typeahead.test.tsx
- adds missing story
- adds onChange to prop
- changes onSearch to be async
> fix(typeahead): add some missing props to typeahead component

- .gitignore
- tsconfig.json
- fixes tsconfig.json file
- unifies all tsconfig.json files across all projects
> build(tsconfig.json): remove unused TS configurations and fixes builds

- src/components/Toaster/strings.ts
- stories/toaster.stories.tsx
- test/__snapshots__/toaster.test.tsx.snap
- test/toaster.test.tsx
Adds some tests to Toaster component.
> test(toaster): adds some toaster tests

- src/components/Navbar/Navbar.tsx
- src/components/Navbar/interfaces.tsx
- stories/navbar.stories.tsx
Added a navbar dropdown component that uses an icon instead of text. 
Fixes #[1948](https://github.com/HospitalRun/hospitalrun-frontend/issues/1948)
> feat(navbar): icon based navbar dropdown

- .github/workflows/ci.yml
Fix checkout issue on ci pipeline
> ci(action): fix release checkout

- stories/navbar.stories.tsx
The image on the navbar story was broken as you can see on the live version or on this image
> fix(navbar): nav bar icon broken

- src/components/Badge/Badge.tsx
- src/components/Button/Button.tsx
- src/components/Modal/Modal.tsx
- stories/alerts.stories.tsx
- stories/badges.stories.tsx
- stories/buttons.stories.tsx
Improve on https://github.com/HospitalRun/components/issues/238 
- missing default specification on the main component 
- adjust the selection on boolean and the list selection on the existing stories
- fix the documentation and playground for the button and badges stories
*Note: pull requests without proper descriptions may simply be closed without further discussion. We appreciate your contributions, but need to know what you are offering in clearly described format. Provide tests for all code that you add/modify. If you add/modify any components update the storybook. Thanks! (you can delete this text)*
> docs: update badges and button docs

- stories/icons.stories.tsx
- test/icon.test.tsx
Fixes #676.
- Added the up and down arrow icons to the Storybook interface.
- Added Jest tests to check for up and down arrow icons.
> chore(icons): added tests and Storybook elements for arrow icons
